spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/sboot_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: 123456
  redis:
    port: 6379
    host: 127.0.0.1
    connect-timeout: 5000
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springfox:
  documentation:
    swagger-ui:
      enabled: true

feign:
  client:
    config:
      sboot-quartz:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

#jwt:
#  config:
#    key: Cc%ijAMvodvDl15C6UkUBSsA!E&D%ram^uQ#aK#gZWVx1Yq1TNI!$YS0qaTYd17#