server:
  port: 8080
  servlet:
    context-path: /sboot

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/adminly?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  redis:
    port: 6379
    host: 127.0.0.1
    connect-timeout: 5000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    aggressive-lazy-loading: true

shiro:
  login-url: /auth/login
  anons:
    - /auth/login
    - /auth/register
    - /swagger-ui/**
    - /swagger-resources/**
    - /webjars/**
    - /v3/**
  authcs:
    - /**
  hash-algorithm: MD5
  hash-iterations: 1024

sboot:
  single-login: false

springfox:
  documentation:
    swagger-ui:
      enabled: true


#jwt:
#  config:
#    key: Cc%ijAMvodvDl15C6UkUBSsA!E&D%ram^uQ#aK#gZWVx1Yq1TNI!$YS0qaTYd17#