server:
  port: 8083

spring:
  application:
    name: sboot-tools

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  mail:
    host: smtp.qq.com
    username: zhanglongyue@vip.qq.com
    password: qdvinliatedvbife
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/sboot_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: 123456

  redis:
    port: 6379
    host: 127.0.0.1
    connect-timeout: 5000

  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 123456

shiro:
  login-url: /auth/login
  anons:
    - /auth/login
    - /auth/logout
    - /auth/register
    - /swagger-ui/**
    - /swagger-resources/**
    - /webjars/**
    - /v3/**
    - /images/**
    - /websocket/**
  authcs:
    - /**
  hash-algorithm: MD5
  hash-iterations: 1024
