server:
  port: 8080
  servlet:
    context-path: /shiro

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_shiro?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  redis:
    port: 6379
    password: 123456
    host: 127.0.0.1
    connect-timeout: 5000

shiro:
  login-url: /login
  anons:
    - /login.html
    - /index.html
    - /login
    - /register
    - /register.html
  authcs:
    - /**
  hashAlgorithm: MD5
  hashIterations: 1024
