server:
  port: 8080
  servlet:
    context-path: /shiro

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/adminly?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  redis:
    port: 6379
    host: 127.0.0.1
    connect-timeout: 5000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

shiro:
  login-url: /auth/login
  anons:
    - auth/login.html
    - index.html
    - /auth/login
    - /auth/logout
    - /auth/register
    - /auth/goRegister
    - auth/register.html
  authcs:
    - /**
  hashAlgorithm: MD5
  hashIterations: 1024
  redisHost: ${spring.redis.host}:${spring.redis.port}
  redisTimeOut: ${spring.redis.connect-timeout}

#jwt:
#  config:
#    key: Cc%ijAMvodvDl15C6UkUBSsA!E&D%ram^uQ#aK#gZWVx1Yq1TNI!$YS0qaTYd17#
